### ISSUE TITLE
Request - Drinks!

### ISSUE THREAD

**Issue by UmbraZeal** [kristkos/kctg-common#2]
First of all I love this mod a ton, it's been a great addition and my players love it.

I was wondering if you would ever add drinks into the module, generic ones like ale and wine but also race specific ones like something Elves would drink and Goblin or Orc-ish drinks.

**Comment by kristkos** [comment]
Funny enough, someone was also interested in food as processed goods for inns and the like. (wines, cheeses, etc)
And was thinking of making that my next pack. 
But it will take a bit up until that comes to fruition, as I have been called back to work temporarily and my time has become very limited as I work on a mixture of shifts and when I come back home I am very tired. 
And I have some ideas brewing that revolve around food too, as it was one of my favorite packs I've made :D

**Comment by UmbraZeal** [comment]
I wish you all the luck with work and look forward to the next update!
