### ISSUE TITLE
[Bug] Foundry v11 Build 299 unable to validate module metadata

### ISSUE THREAD

**Issue by chaoticnote** [kristkos/kctg-common#3]
Metadata validation failed for module "kctg-common": Module validation errors:
  packs: Compendium "Common" name is not unique.

**Comment by kristkos** [comment]
Thank you for the Issue, however, this has been fixed with version 0.12a. Please uninstall and reinstall.
If the error persists, please update to the stable latest build (11.304?), as well as, the method of hosting.
