### ISSUE TITLE
v11 Module Validation Error

### ISSUE THREAD

**Issue by maplealmond** [kristkos/kctg-common#4]
When installed on v11, kctg-common has the following validation error (visible from the setup screen)

Module validation errors:
  packs: 
    0: Duplicate Compendium name "Common" already declared by some other pack
    1: Duplicate Compendium name "Common" already declared by some other pack

**Comment by kristkos** [comment]
Thank you for the Issue, however, this has been fixed with version 0.12a. Please uninstall and reinstall.
If the error persists, please provide me full version number (11.304?), as well as, the method of hosting.

**Comment by maplealmond** [comment]
The issue may be with Forge, as it is not picking up 0.12a as a valid version number.  kctg-common shows up as only v0.12

I notice that the manifest still references "https://github.com/kristkos/kctg-common/releases/download/0.12/module.json" which might be preventing forge (and possibly others) from seeing the new release, hence requiring uninstall and reinstall.

**Comment by kristkos** [comment]
Thank you for the additional info. I've pushed a version 0.13, just to clear any issues that Forge might had, tested on my both instances, both windows and ubuntu and received no errors. 

Can you please let me know if you still receive the error.

**Comment by maplealmond** [comment]
Confirmed both that Forge has picked up 0.13 and that the error no longer appears.  Thank you!
